### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Bilal268** [sthysel/ops241#1]
I m a beginner and having an issue regarding library ops241-radar. it is giving a syntax error at line 328 that is about baud rate.
it is also giving error (Non-ASCII character '\xe2'). the version that i am using is 2.7.15

**Comment by omnipresense** [comment]
Hello Bilal,

Which depository are you using?

Note the default baud rate for the OPS24x sensors is 19200.  Most systems like Arduino like to start at 9600.  So make sure your baud rate matches.

The version 2.7.15 refers to what code?

Thanks,

Sandy

**Comment by omnipresense** [comment]
I just observed that there's a stray comma at the end of the prior line
```
            timeout=0.01,
            writeTimeout=2,
        )
```
Could you remove it and see what happens?  IF that fixes it, could you make a pull request and maybe @sthysel will merge it?

re: 2.7.15: Are you using Python 2?  Python 2 has passed its end-of-life date earlier this year.  
Thanks

**Comment by sthysel** [comment]
@Bilal268 you need to be more specific about your error, post the stack trace here. Python 2 is not supported by this repo, and will never be. I suggest you move over to Python 3.8 or at least Python 3.6. Did you install from pip or from this master source ? I have not played with the ops241 in a year so so perhaps the repo code base has moved on from the pip lib I released when I actively worked on it.

@omnipresense, the 'stray' comma is there by design. It reduces diff noise as any extra parameters to a call will incur deltas on one code line, not two. Its commonish practice.

**Comment by jimwhitfield** [comment]
Thanks for replying, @sthysel !, and insight into the trailing comma.

**Comment by Bilal268** [comment]
When used python 3.7 for this code. It resolved all issues. thanks
